import type { Metadata } from "next";
import { Providers } from './Providers';
import { ReactNode } from 'react';
import "./globals.css";
import "./index.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="vi">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}